site_name: NasixJS Docs
repo_name: 'nasix.js'
repo_url: 'https://github.com/steviebeenz/nasix.js'
edit_uri: ''
copyright: "Nasix.js Docs"
theme:
  name: 'material'
  favicon: 'na6.png'
  logo: 'na6.png'
  feature:
    tabs: false
google_analytics:
  - UA-123568344-4
  - auto
  
